server:
  port: 13371

spring:
#邮件配置
  mail:
    #邮件服务器地址
    host: smtp.163.com
    #协议
    protocol: smtp
    #编码格式
    default-encoding: UTF-8
    #邮箱地址
    username: leil1024@163.com
    #端口号
    port: 25
    #邮箱smtp授权码
    password: LMGCSSMSXDEZGOHO

  #消息队列服务
  rabbitmq:
    #用户名
    username: leil
    #密码
    password: 123456
    #服务器地址
    host: 192.168.14.152
    #端口号
    port: 5672

