spring:
  #热部署
  devtools:
    restart:
      enabled: false

  #数据源
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/yoa?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver


  #redis
  redis:
    host: 192.168.14.152
    port: 6379
    database: 0

  #消息队列服务
  rabbitmq:
    #用户名
    username: leil
    #密码
    password: 123456
    #服务器地址
    host: 192.168.14.152
    #端口号
    port: 5672
    #消息确认回调
    publisher-confirm-type: correlated
    #消息失败回调
    publisher-returns: true

  thymeleaf:
    prefix: classpath:/templates

  #文件上传
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 10MB
#端口号
server:
  port: 13370
  servlet:
    encoding:
      charset: UTF-8
      force: true

#打印mapper中的sql
logging:
  level:
    com.yoa.mapper: debug
